name: pre-commit

on:
  pull_request:
  push:
     branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
      with:
        # Ensure the full history is fetched
        # This is required to run pre-commit on a specific set of commits
        # TODO: Remove this when all the pre-commit issues are fixed
        fetch-depth: 0
    - uses: actions/setup-python@v5.1.1
      with:
        python-version: 3.13
    - uses: pre-commit/action@v3.0.1
